#!/usr/bin/env bash
#Generating RSA key pair with 4096 bits, named 'school'
ssh-keygen -t rsa -b 4096 -f school

#Add paraphrase 'betty' to the private key
echo 'betty' | ssh-keygen -p -P "" -N 'betty' -f school
