#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5803-webs
    bind *:80
    mode http
    balance roundrobin
    server 5804-web-01 3.89.55.73:80 check
    server 5803-web-02 107.22.149.20:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
