#!/usr/bin/env bash
#Transfers files from the clients to a server

#Check if the number of arguments is less than 4 and display usage
if [ "$#" -lt 4 ]; then
   echo "Usage: $0-transfer_file web_page.html 3.89.55.73 ubuntu ~/.ssh/school"
   exit 1
fi
#Assigning arguments to descriptive variables
file_to_transfer="$1"
remote_ip="$3"
remote_user="$4"
ssh_key_path="$5

#Tranfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path"" "$file_to_transfer" $remote_user@$remote_ip":~/
