#!/usr/bin/env bash
# Transfers files from the clients to a server

# Check if the number of arguments is less than 4 and display usage
if [ "$#" -lt 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
"
   exit 1
fi
# Assigning arguments to descriptive variables
PATH_TO_SSH_KEY="$1"
PATH_TO_FILE="$2"
USERNAME="$3"
IP="$4"

# Tranfer
scp -o "StrictHostKeyChecking no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP"