#!/usr/bin/env bash
# a Bash script that sets up Nginx on a server.

apt update
apt install -y nginx

echo "<html><body>Holberton School</body></html>" > /var/www/html/index.html

service nginx restart

