#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee  /var/www/html/index.html > /dev/null
sudo kill -s HUP $(cat /var/run/nginx.pid)

output=$(curl -s http://localhost)  # Query localhost as it's the server itself

# Check if the output contains "Holberton School"
if [[ $output == *"Holberton School"* ]]; then
    echo "Holberton School string found in Nginx root page"
else
    echo "Holberton School string not found in Nginx root page"
    exit 1
fi

