#!/bin/bash

# Check if Nginx is installed, install if not
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get install nginx -y
fi

# Create or update the configuration file for redirection
sudo tee /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name 5803-web-01;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Redirect all other requests to prevent access
    location / {
        return 404;
    }
}
EOF

# Enable or update the redirection configuration by creating a symbolic link
if [ ! -f /etc/nginx/sites-enabled/redirect_me ]; then
    sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
fi

# Test Nginx configuration
sudo nginx -t

# Reload Nginx to apply changes
sudo systemctl reload nginx
