#!/usr/bin/env bash

# Function to display usage and exit on incorrect arguments
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

# Check if correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    usage
fi

# Assigning arguments to descriptive variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Install nginx
apt-get update
apt-get install -y nginx

# Create Nginx directories and set up index.html
mkdir -p /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html

# Configure Nginx server block
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /etc/nginx/html;
    index       index.html index.htm;

    location /redirect_me {
        return 301 http://youtube.com/;
    }
}
EOF

# Restart Nginx service
service nginx restart

# Transfer file using scp
scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if file transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi

